version: '3.1'

services:
  redis:
    image: redislabs/redismod
    container_name: redis
    environment:
      - REDIS_APPENDONLY=yes
    ports:
      - "6379:6379"
    volumes:
      - ./redis-data:/mnt/e/codee/e-commerce/var/lib/redis/data